import { MongoClient, ObjectId, ServerApiVersion } from 'mongodb';
import bcrypt from 'bcrypt';
import dotenv from 'dotenv';

dotenv.config({ path: '.env' });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/rentivo';
const SALT_ROUNDS = 10;

const demoProperties = [
  {
    title: 'Sunlit Studio in Williamsburg',
    shortDescription: 'Bright studio with exposed brick in the heart of Williamsburg.',
    description: 'Bright and airy studio apartment in the heart of Williamsburg. Features exposed brick walls, hardwood floors, and floor-to-ceiling windows. Walking distance to L train, cafes, and boutiques. Perfect for young professionals who love the Brooklyn vibe.',
    price: 2200,
    location: 'Brooklyn, NY',
    propertyType: 'studio' as const,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    status: 'active' as const,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'ac', 'kitchen', 'hardwood'],
    size: 450,
    balconies: 0,
    floor: 3,
    totalFloors: 5,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 2200,
    advancePayment: 1100,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking indoors. Quiet hours after 10pm. No pets allowed.',
    rentalTerms: 'First month and security deposit due at signing. Late fee of $50 after 5-day grace period. Tenant insurance required.',
    fullAddress: '248 Bedford Ave, Brooklyn, NY 11211',
    lat: 40.7142,
    lng: -73.9614,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Modern 2BR Apartment with Manhattan Views',
    shortDescription: 'Stunning two-bedroom with panoramic Manhattan skyline views.',
    description: 'Stunning two-bedroom apartment with panoramic Manhattan skyline views. Floor-to-ceiling windows flood the space with natural light. Updated kitchen with granite countertops and stainless steel appliances. Building amenities include rooftop deck, gym, and 24/7 doorman.',
    price: 3800,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['wifi', 'gym', 'doorman', 'elevator', 'ac', 'kitchen', 'dishwasher', 'views'],
    size: 950,
    balconies: 1,
    floor: 12,
    totalFloors: 20,
    furnishing: 'semi-furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 3800,
    advancePayment: 3800,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Quiet hours 10pm-8am. Guest policy: max 2 overnight guests.',
    rentalTerms: 'First month, last month, and security deposit due at signing. Background and credit check required. Minimum income 40x monthly rent.',
    fullAddress: '350 W 42nd St, Manhattan, NY 10036',
    lat: 40.7580,
    lng: -73.9920,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Cozy Room in Shared Brownstone',
    shortDescription: 'Private room in a charming Brooklyn brownstone.',
    description: 'Private room in a charming Brooklyn brownstone. Shared kitchen and living areas with friendly roommates. Quiet tree-lined street, close to Prospect Park. Includes all utilities and high-speed WiFi. Great for students or remote workers.',
    price: 1100,
    location: 'Brooklyn, NY',
    propertyType: 'room' as const,
    images: ['https://images.unsplash.com/photo-1598928506311-c55ez637a4c1?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'kitchen', 'furnished'],
    size: 200,
    balconies: 0,
    floor: 2,
    totalFloors: 3,
    furnishing: 'furnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 1100,
    advancePayment: 550,
    leaseDuration: 6,
    minStay: 3,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'Shared spaces must be kept clean. No overnight guests without notice.',
    rentalTerms: 'Month-to-month after initial 6-month lease. 30-day notice required to vacate.',
    fullAddress: '112 Prospect Pl, Brooklyn, NY 11238',
    lat: 40.6782,
    lng: -73.9698,
    availableFrom: new Date('2026-07-15'),
  },
  {
    title: 'Luxury Villa with Private Garden',
    shortDescription: 'Exclusive four-bedroom villa with a private garden and patio.',
    description: 'Exclusive four-bedroom villa in Riverdale with a private garden and patio. Spacious open-plan living, chef\'s kitchen, and home office. Two-car garage, washer/dryer, and central air. Perfect for families seeking suburban tranquility within city limits.',
    price: 6500,
    location: 'Riverdale, NY',
    propertyType: 'villa' as const,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    status: 'active' as const,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ['wifi', 'parking', 'pool', 'gym', 'ac', 'balcony', 'fireplace', 'kitchen', 'garage', 'garden', 'patio', 'washer/dryer'],
    size: 3200,
    balconies: 2,
    floor: 1,
    totalFloors: 2,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 13000,
    advancePayment: 6500,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pets welcome with deposit. Pool hours: 8am-10pm.',
    rentalTerms: '24-month lease required. Security deposit equals 2 months rent. Early termination penalty: 3 months rent. Tenant responsible for garden maintenance.',
    fullAddress: '45 Riverdale Ave, Bronx, NY 10463',
    lat: 40.8955,
    lng: -73.9143,
    availableFrom: new Date('2026-08-15'),
  },
  {
    title: 'Charming House near Central Park',
    shortDescription: 'Charming townhouse steps from Central Park.',
    description: 'Beautiful three-story townhouse steps from Central Park. Original details meet modern updates — crown molding, fireplace, renovated bathrooms. Private backyard with mature trees. Ideal for those who want park access without leaving the city.',
    price: 5200,
    location: 'Manhattan, NY',
    propertyType: 'house' as const,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    status: 'active' as const,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['wifi', 'parking', 'fireplace', 'hardwood', 'balcony', 'kitchen', 'garden', 'furnished'],
    size: 2100,
    balconies: 1,
    floor: 1,
    totalFloors: 3,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 5200,
    advancePayment: 5200,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Well-behaved pets welcome. Please respect quiet hours after 9pm.',
    rentalTerms: '12-month lease. First month and security deposit due at move-in. Tenant responsible for yard maintenance.',
    fullAddress: '210 W 81st St, Manhattan, NY 10024',
    lat: 40.7831,
    lng: -73.9762,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Affordable Apartment in Astoria',
    shortDescription: 'Bright and affordable apartment in vibrant Astoria.',
    description: 'Well-maintained one-bedroom apartment in vibrant Astoria. Near N/W trains, diverse restaurants, and Astoria Park. Features updated kitchen, good closet space, and laundry in building. Heat and hot water included in rent.',
    price: 1800,
    location: 'Queens, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'ac', 'kitchen'],
    size: 650,
    balconies: 0,
    floor: 4,
    totalFloors: 6,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 1800,
    advancePayment: 900,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Heat and hot water included. Laundry in basement.',
    rentalTerms: '12-month lease. One month security deposit. No pets allowed per building policy.',
    fullAddress: '31-15 Ditmars Blvd, Queens, NY 11105',
    lat: 40.7723,
    lng: -73.9196,
    availableFrom: new Date('2026-07-01'),
  },
  {
    title: 'Penthouse Loft in SoHo',
    shortDescription: 'Stunning penthouse loft with panoramic city views.',
    description: 'Spectacular penthouse loft with 14-foot ceilings and skylights in prime SoHo. Open floor plan with chef\'s kitchen, spa-like bathroom, and private terrace with city views. Building has elevator, bike storage, and roof access.',
    price: 8500,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['wifi', 'elevator', 'balcony', 'hardwood', 'ac', 'bike', 'kitchen', 'dishwasher', 'views', 'patio'],
    size: 1800,
    balconies: 1,
    floor: 6,
    totalFloors: 6,
    furnishing: 'furnished' as const,
    condition: 'new' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 8500,
    advancePayment: 8500,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No shoes on hardwood floors. Bike storage in basement.',
    rentalTerms: '12-month lease. Two months security deposit. No subletting without written approval.',
    fullAddress: '78 Greene St, Manhattan, NY 10012',
    lat: 40.7247,
    lng: -74.0010,
    availableFrom: new Date('2026-10-01'),
  },
  {
    title: 'Quiet Studio near Columbia University',
    shortDescription: 'Peaceful studio perfect for students and academics.',
    description: 'Compact but efficient studio apartment near Columbia University campus. Perfect for graduate students or faculty. Recently renovated with new appliances. Close to M4 bus, 1 train, and Riverside Park.',
    price: 1650,
    location: 'Manhattan, NY',
    propertyType: 'studio' as const,
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    status: 'active' as const,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'kitchen', 'furnished'],
    size: 380,
    balconies: 0,
    floor: 2,
    totalFloors: 5,
    furnishing: 'furnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 1650,
    advancePayment: 825,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets. Quiet building — please keep noise down.',
    rentalTerms: '12-month lease. First month and security deposit due at signing. Student references required.',
    fullAddress: '520 W 114th St, Manhattan, NY 10025',
    lat: 40.8065,
    lng: -73.9629,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Spacious 3BR in Park Slope',
    shortDescription: 'Family-friendly three-bedroom in coveted Park Slope.',
    description: 'Generous three-bedroom apartment on a beautiful tree-lined block in Park Slope. Original hardwood floors, eat-in kitchen, and large living room. Walking distance to Prospect Park, the farmers market, and top-rated schools.',
    price: 4200,
    location: 'Brooklyn, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
    status: 'active' as const,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['wifi', 'laundry', 'hardwood', 'dishwasher', 'storage', 'kitchen', 'garden'],
    size: 1400,
    balconies: 1,
    floor: 2,
    totalFloors: 4,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 4200,
    advancePayment: 2100,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Pets allowed with additional deposit. Shared backyard.',
    rentalTerms: '12-month lease. One month security deposit. Pet deposit of $500 additional.',
    fullAddress: '345 7th Ave, Brooklyn, NY 11215',
    lat: 40.6681,
    lng: -73.9822,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Bright Room in Harlem Brownstone',
    shortDescription: 'Sunny room in a historic Harlem brownstone.',
    description: 'Sunny room available in a shared brownstone in Harlem. Full bathroom, shared kitchen with all essentials, and access to a lovely garden. Close to A/B/C/D trains, Sylvia\'s, and the Apollo Theater. Diverse and welcoming neighborhood.',
    price: 950,
    location: 'Manhattan, NY',
    propertyType: 'room' as const,
    images: ['https://images.unsplash.com/photo-1595514535415-dae8580c416c?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'balcony', 'kitchen', 'garden', 'furnished'],
    size: 180,
    balconies: 0,
    floor: 1,
    totalFloors: 3,
    furnishing: 'furnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 950,
    advancePayment: 475,
    leaseDuration: 6,
    minStay: 3,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'Shared spaces. Keep kitchen clean after use. No overnight guests.',
    rentalTerms: 'Month-to-month after initial 6-month term. 30-day written notice to vacate.',
    fullAddress: '207 W 133rd St, Manhattan, NY 10027',
    lat: 40.8115,
    lng: -73.9465,
    availableFrom: new Date('2026-07-01'),
  },
  {
    title: 'Waterfront Condo in Long Island City',
    shortDescription: 'Modern waterfront condo with stunning East River views.',
    description: 'Modern waterfront condominium with stunning East River views. Floor-to-ceiling windows, in-unit washer/dryer, and gourmet kitchen. Building amenities include pool, fitness center, concierge, and parking garage.',
    price: 3400,
    location: 'Queens, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['wifi', 'parking', 'pool', 'gym', 'laundry', 'doorman', 'elevator', 'kitchen', 'dishwasher', 'views', 'washer/dryer'],
    size: 1100,
    balconies: 1,
    floor: 8,
    totalFloors: 15,
    furnishing: 'semi-furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 3400,
    advancePayment: 3400,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Pool hours: 6am-10pm. Concierge available 24/7.',
    rentalTerms: '12-month lease. Two months security deposit. Amenities fee: $200/month included in rent.',
    fullAddress: '46-30 Center Blvd, Queens, NY 11109',
    lat: 40.7473,
    lng: -73.9530,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Renovated House in Staten Island',
    shortDescription: 'Fully renovated house with private backyard.',
    description: 'Fully renovated four-bedroom colonial in a quiet Staten Island neighborhood. New kitchen, bathrooms, and roof. Large backyard with deck, perfect for entertaining. Two-car driveway, finished basement, and central air conditioning.',
    price: 3200,
    location: 'Staten Island, NY',
    propertyType: 'house' as const,
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'],
    status: 'active' as const,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ['wifi', 'parking', 'ac', 'balcony', 'fireplace', 'storage', 'kitchen', 'garage', 'garden', 'patio'],
    size: 2400,
    balconies: 1,
    floor: 1,
    totalFloors: 2,
    furnishing: 'unfurnished' as const,
    condition: 'new' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'included' as const,
    internet: false,
    securityDeposit: 3200,
    advancePayment: 3200,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pets welcome. Maintain the garden. Two-car garage included.',
    rentalTerms: '24-month lease required. Security deposit equals 1 month rent. Tenant responsible for internet setup and utilities.',
    fullAddress: '89 Clove Rd, Staten Island, NY 10301',
    lat: 40.6105,
    lng: -74.1157,
    availableFrom: new Date('2026-09-15'),
  },
  {
    title: 'Luxury Penthouse with Panoramic City Views',
    shortDescription: 'Breathtaking penthouse with 360-degree city views.',
    description: 'Experience unparalleled luxury in this stunning penthouse apartment perched on the top floor of a premier building in the Upper East Side. Floor-to-ceiling windows wrap around the entire residence, offering breathtaking 360-degree views of Central Park, the Manhattan skyline, and the East River. The open-concept living space features imported Italian marble floors, a gourmet chef\'s kitchen with Sub-Zero and Wolf appliances, and a private terrace perfect for al fresco dining. The primary suite includes a spa-like bathroom with heated floors, a soaking tub, and a walk-in closet. Additional highlights include a home office, wine cellar, and smart home automation throughout.',
    price: 12500,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    status: 'active' as const,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ['wifi', 'gym', 'pool', 'doorman', 'elevator', 'ac', 'balcony', 'fireplace', 'kitchen', 'dishwasher', 'hardwood', 'laundry', 'storage', 'bike', 'views', 'patio', 'washer/dryer'],
    size: 2800,
    balconies: 2,
    floor: 42,
    totalFloors: 42,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 25000,
    advancePayment: 12500,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside the property. Quiet hours observed from 10pm to 8am. Maximum 2 overnight guests without prior approval. No short-term subletting. All guests must be registered with the doorman. Building amenities available 6am-10pm. Please respect neighbors and keep noise to a minimum in common areas.',
    rentalTerms: 'Lease requires first month rent, security deposit (2 months), and advance payment (1 month). Tenant responsible for electricity and internet utilities. Water and gas included. Annual rent escalation of 3% applies. Early termination requires 90-day written notice and penalty of 2 months rent. Tenant insurance required. Background and credit check mandatory. Minimum household income requirement: 40x monthly rent.',
    fullAddress: '1000 Fifth Avenue, Penthouse A, New York, NY 10028',
    lat: 40.7831,
    lng: -73.9654,
    availableFrom: new Date('2026-10-01'),
  },
  {
    title: 'Artist Loft in DUMBO',
    shortDescription: 'Industrial-chic loft with exposed beams and river views.',
    description: 'Converted warehouse loft in the heart of DUMBO with soaring 16-foot ceilings, original exposed brick, and massive arched windows overlooking the East River and Manhattan Bridge. Open-concept layout perfect for creative professionals. Features concrete floors, industrial lighting, and a custom-built kitchen island. Steps from Brooklyn Bridge Park, waterfront dining, and the A/C trains.',
    price: 4800,
    location: 'Brooklyn, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'elevator', 'hardwood', 'ac', 'kitchen', 'dishwasher', 'views', 'bike', 'storage'],
    size: 1200,
    balconies: 0,
    floor: 4,
    totalFloors: 5,
    furnishing: 'semi-furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 4800,
    advancePayment: 4800,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Pets welcome. Bike storage available. Freight elevator for moving.',
    rentalTerms: '12-month lease. Two months security deposit. No subletting without approval.',
    fullAddress: '55 Washington St, Brooklyn, NY 11201',
    lat: 40.7033,
    lng: -73.9890,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Sunny 1BR in Hell\'s Kitchen',
    shortDescription: 'Bright one-bedroom in the heart of Hell\'s Kitchen.',
    description: 'Cheerful one-bedroom apartment on a quiet side street in Hell\'s Kitchen. South-facing windows fill the space with sunshine all day. Renovated kitchen with quartz counters and new appliances. Walking distance to Times Square, Broadway theaters, and the Hudson River Greenway. Laundry in building.',
    price: 2900,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'ac', 'kitchen', 'hardwood', 'elevator'],
    size: 600,
    balconies: 0,
    floor: 7,
    totalFloors: 12,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 2900,
    advancePayment: 1450,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets. Quiet hours 10pm-8am.',
    rentalTerms: '12-month lease. One month security deposit. Heat and hot water included.',
    fullAddress: '320 W 48th St, Manhattan, NY 10036',
    lat: 40.7614,
    lng: -73.9870,
    availableFrom: new Date('2026-07-15'),
  },
  {
    title: 'Family Home in Bay Ridge',
    shortDescription: 'Spacious detached home with driveway and backyard.',
    description: 'Well-maintained detached colonial in a family-friendly Bay Ridge neighborhood. Features four bedrooms, two full bathrooms, eat-in kitchen, and finished basement. Private driveway fits two cars, and the fenced backyard has a built-in barbecue. Close to the R train, Owl\'s Head Park, and the waterfront promenade.',
    price: 3800,
    location: 'Brooklyn, NY',
    propertyType: 'house' as const,
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
    status: 'active' as const,
    bedrooms: 4,
    bathrooms: 2,
    amenities: ['wifi', 'parking', 'ac', 'fireplace', 'storage', 'kitchen', 'garage', 'garden', 'patio', 'washer/dryer'],
    size: 2600,
    balconies: 0,
    floor: 1,
    totalFloors: 2,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 3800,
    advancePayment: 3800,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pets welcome. Maintain yard. No loud music after 9pm.',
    rentalTerms: '24-month lease. Security deposit equals 1 month rent. Tenant responsible for all utilities and lawn care.',
    fullAddress: '420 76th St, Brooklyn, NY 11209',
    lat: 40.6350,
    lng: -74.0250,
    availableFrom: new Date('2026-08-15'),
  },
  {
    title: 'Modern Studio in Financial District',
    shortDescription: 'Sleek studio with floor-to-ceiling windows in FiDi.',
    description: 'Contemporary studio in a luxury high-rise in the Financial District. Floor-to-ceiling windows with harbor views, walk-in closet, and modern bathroom with rainfall shower. Building features 24-hour concierge, rooftop pool, and state-of-the-art fitness center. Steps from the 2/3/4/5 trains and the Oculus.',
    price: 2600,
    location: 'Manhattan, NY',
    propertyType: 'studio' as const,
    images: ['https://images.unsplash.com/photo-1600566753051-f0b892805c26?w=800'],
    status: 'active' as const,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ['wifi', 'gym', 'pool', 'doorman', 'elevator', 'ac', 'kitchen', 'laundry', 'views', 'washer/dryer'],
    size: 500,
    balconies: 0,
    floor: 18,
    totalFloors: 35,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 2600,
    advancePayment: 2600,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets. Gym hours 5am-11pm. Pool hours 7am-9pm.',
    rentalTerms: '12-month lease. One month security deposit. Amenity fee included in rent.',
    fullAddress: '75 Wall St, Manhattan, NY 10005',
    lat: 40.7063,
    lng: -74.0094,
    availableFrom: new Date('2026-07-01'),
  },
  {
    title: 'Charming Room in Bushwick',
    shortDescription: 'Cozy room in a vibrant Bushwick shared apartment.',
    description: 'Private room in a three-bedroom shared apartment in the heart of Bushwick\'s art district. Shared bathroom and fully equipped kitchen. The neighborhood is alive with galleries, street art, live music venues, and some of the best taco spots in the city. Close to the L train for easy Manhattan access.',
    price: 1050,
    location: 'Brooklyn, NY',
    propertyType: 'room' as const,
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'kitchen', 'laundry', 'furnished', 'ac'],
    size: 220,
    balconies: 0,
    floor: 3,
    totalFloors: 4,
    furnishing: 'furnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 1050,
    advancePayment: 525,
    leaseDuration: 6,
    minStay: 3,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'Shared spaces must be cleaned after use. No overnight guests. Respect quiet hours.',
    rentalTerms: '6-month lease. Month-to-month after. 30-day notice to vacate.',
    fullAddress: '189 Irving Ave, Brooklyn, NY 11237',
    lat: 40.6991,
    lng: -73.9092,
    availableFrom: new Date('2026-07-15'),
  },
  {
    title: 'Elegant 2BR in Upper West Side',
    shortDescription: 'Pre-war elegance with modern updates on the Upper West Side.',
    description: 'Graceful two-bedroom in a classic pre-war building on the Upper West Side. Original details include crown molding, arched doorways, and hardwood parquet floors. Updated kitchen with butcher block counters and stainless appliances. Bright corner unit with windows on two sides. Building has a beautiful courtyard garden and bike room.',
    price: 4100,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'hardwood', 'ac', 'kitchen', 'elevator', 'garden', 'storage', 'bike'],
    size: 900,
    balconies: 0,
    floor: 5,
    totalFloors: 8,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 4100,
    advancePayment: 4100,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Quiet building. No construction without board approval.',
    rentalTerms: '12-month lease. One month security deposit. Board application fee: $500. Pet deposit: $500 if approved.',
    fullAddress: '220 W 93rd St, Manhattan, NY 10025',
    lat: 40.7920,
    lng: -73.9720,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Beach Cottage in Rockaway',
    shortDescription: 'Steps from the beach in Rockaway Park.',
    description: 'Charming two-bedroom cottage just two blocks from the beach in Rockaway Park. Open living and dining area, updated kitchen, and a private deck perfect for summer evenings. Enjoy surfing, boardwalk strolls, and the laid-back beach lifestyle while still being just an hour from Midtown via the A train.',
    price: 2400,
    location: 'Queens, NY',
    propertyType: 'house' as const,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'parking', 'ac', 'kitchen', 'patio', 'garden', 'furnished'],
    size: 950,
    balconies: 0,
    floor: 1,
    totalFloors: 1,
    furnishing: 'furnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 2400,
    advancePayment: 1200,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pets welcome. Please remove sand before entering. Deck furniture provided.',
    rentalTerms: '12-month lease. One month security deposit. Summer months (June-August) may have adjusted rates.',
    fullAddress: '142 Beach 129th St, Rockaway Park, NY 11694',
    lat: 40.5834,
    lng: -73.8356,
    availableFrom: new Date('2026-07-01'),
  },
  {
    title: 'High-Rise 1BR in Hudson Yards',
    shortDescription: 'Sleek one-bedroom in the newest Manhattan neighborhood.',
    description: 'Sophisticated one-bedroom in a glass tower at Hudson Yards. Floor-to-ceiling windows frame stunning Hudson River views. Chef\'s kitchen with Miele appliances, spa bathroom with Duravit fixtures, and motorized shades. Building amenities include infinity pool, private dining room, children\'s playroom, and valet parking.',
    price: 5500,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'gym', 'pool', 'doorman', 'elevator', 'ac', 'kitchen', 'dishwasher', 'views', 'washer/dryer', 'storage', 'parking'],
    size: 750,
    balconies: 1,
    floor: 28,
    totalFloors: 40,
    furnishing: 'furnished' as const,
    condition: 'new' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 5500,
    advancePayment: 5500,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets over 40lbs. Pool and gym require reservation. Valet parking 24/7.',
    rentalTerms: '12-month lease. Two months security deposit. Amenities fee included. Renter\'s insurance required.',
    fullAddress: '15 Hudson Yards, Unit 28F, New York, NY 10001',
    lat: 40.7537,
    lng: -74.0020,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Industrial Studio in Red Hook',
    shortDescription: 'Raw industrial space converted to a live-work studio.',
    description: 'Unique industrial studio in a converted waterfront warehouse in Red Hook. Soaring ceilings, polished concrete floors, and oversized factory windows with views of the harbor and Statue of Liberty. Open layout ideal for artists, designers, or anyone who needs space to create. Near IKEA, Fairway Market, and the Red Hook ferry.',
    price: 2100,
    location: 'Brooklyn, NY',
    propertyType: 'studio' as const,
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800'],
    status: 'active' as const,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ['wifi', 'hardwood', 'ac', 'kitchen', 'storage', 'views', 'elevator'],
    size: 550,
    balconies: 0,
    floor: 2,
    totalFloors: 3,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 2100,
    advancePayment: 1050,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'allowed' as const,
    houseRules: 'Smoking allowed in designated areas. Pets case-by-case. No loud power tools after 7pm.',
    rentalTerms: '12-month lease. One month security deposit. Live-work use permitted.',
    fullAddress: '160 Imlay St, Brooklyn, NY 11231',
    lat: 40.6746,
    lng: -74.0090,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Spacious Villa in Great Kills',
    shortDescription: 'Expansive family villa with ocean glimpses.',
    description: 'Sprawling five-bedroom villa in the hillside enclave of Great Kills, Staten Island. Multiple living areas, a sun-drenched conservatory, and a gourmet kitchen with double ovens and a walk-in pantry. The landscaped backyard features a heated in-ground pool, gazebo, and mature fruit trees. Two-car attached garage and long driveway. Stunning views of the Atlantic Ocean from the upper level.',
    price: 5800,
    location: 'Staten Island, NY',
    propertyType: 'villa' as const,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    status: 'active' as const,
    bedrooms: 5,
    bathrooms: 4,
    amenities: ['wifi', 'parking', 'pool', 'ac', 'fireplace', 'kitchen', 'garage', 'garden', 'patio', 'washer/dryer', 'storage', 'balcony'],
    size: 4200,
    balconies: 3,
    floor: 1,
    totalFloors: 3,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 11600,
    advancePayment: 5800,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pool maintenance included. No parties over 20 people. Quiet hours 10pm-8am.',
    rentalTerms: '24-month lease. Security deposit equals 2 months rent. Pool season: May-September. Tenant pays for pool heating.',
    fullAddress: '221 Mansion Ave, Staten Island, NY 10308',
    lat: 40.5560,
    lng: -74.1680,
    availableFrom: new Date('2026-08-15'),
  },
  {
    title: 'Cozy 1BR in Greenwich Village',
    shortDescription: 'Classic Village apartment on a tree-lined block.',
    description: 'Charming one-bedroom on one of the most beautiful tree-lined blocks in Greenwich Village. Exposed brick accent wall, original fireplace (decorative), and gleaming hardwood floors. Updated galley kitchen with marble countertops. Steps from Washington Square Park, NYU, and some of the best restaurants in the city.',
    price: 3200,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600566752712-0c28283e10f8?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'hardwood', 'ac', 'kitchen', 'fireplace', 'elevator'],
    size: 550,
    balconies: 0,
    floor: 3,
    totalFloors: 5,
    furnishing: 'semi-furnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 3200,
    advancePayment: 1600,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Small pets considered with deposit. Fireplace decorative only.',
    rentalTerms: '12-month lease. One month security deposit. No guarantors accepted.',
    fullAddress: '45 Commerce St, Manhattan, NY 10014',
    lat: 40.7335,
    lng: -74.0030,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Bright 2BR in Astoria Heights',
    shortDescription: 'Updated two-bedroom with private terrace in Astoria.',
    description: 'Light-filled two-bedroom apartment in the quiet residential enclave of Astoria Heights. Private terrace perfect for morning coffee, updated bathroom with subway tile, and a kitchen with breakfast bar. Close to Triboro Bridge, Astoria Park, and the N/W trains. Minutes to LaGuardia Airport.',
    price: 2500,
    location: 'Queens, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'laundry', 'ac', 'kitchen', 'balcony', 'hardwood'],
    size: 800,
    balconies: 1,
    floor: 3,
    totalFloors: 4,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 2500,
    advancePayment: 1250,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Pets allowed. Street parking available. Quiet residential block.',
    rentalTerms: '12-month lease. One month security deposit. Pet deposit $300.',
    fullAddress: '21-80 31st St, Queens, NY 11105',
    lat: 40.7730,
    lng: -73.9110,
    availableFrom: new Date('2026-07-15'),
  },
  {
    title: 'Executive Suite in Midtown East',
    shortDescription: 'Fully furnished corporate suite in Midtown East.',
    description: 'Turnkey executive suite in a full-service Midtown East building. Completely furnished with designer pieces, fully stocked kitchen, and premium linens. Ideal for relocating professionals or short-term assignments. Building offers maid service, room service from an on-site restaurant, business center, and conference rooms.',
    price: 4500,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'gym', 'doorman', 'elevator', 'ac', 'kitchen', 'dishwasher', 'laundry', 'washer/dryer', 'furnished', 'storage', 'parking'],
    size: 700,
    balconies: 0,
    floor: 15,
    totalFloors: 30,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'available' as const,
    internet: true,
    securityDeposit: 4500,
    advancePayment: 4500,
    leaseDuration: 6,
    minStay: 3,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets. Maid service twice weekly. No loud gatherings after 10pm.',
    rentalTerms: '6-month minimum. Month-to-month after. All utilities and internet included. Maid service included.',
    fullAddress: '303 E 51st St, Manhattan, NY 10022',
    lat: 40.7570,
    lng: -73.9660,
    availableFrom: new Date('2026-07-01'),
  },
  {
    title: 'Garden-Level 2BR in Prospect Heights',
    shortDescription: 'Garden-level apartment with private outdoor space.',
    description: 'Charming garden-level two-bedroom in the sought-after Prospect Heights neighborhood. Private entrance opens to a lovely patio garden — a rare find in the city. Interior features include exposed brick, hardwood floors, and a wood-burning fireplace. Walk to the Brooklyn Museum, Prospect Park, and the 2/3/4/5 trains.',
    price: 3400,
    location: 'Brooklyn, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
    status: 'active' as const,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'hardwood', 'fireplace', 'kitchen', 'garden', 'patio', 'ac', 'storage'],
    size: 850,
    balconies: 0,
    floor: 1,
    totalFloors: 3,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['electricity', 'water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 3400,
    advancePayment: 1700,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Pets welcome. Garden maintained by tenant. Firewood not provided.',
    rentalTerms: '12-month lease. One month security deposit. Garden-level units may have slightly lower natural light.',
    fullAddress: '187 Sterling Pl, Brooklyn, NY 11217',
    lat: 40.6765,
    lng: -73.9750,
    availableFrom: new Date('2026-08-01'),
  },
  {
    title: 'Sun-Drenched 3BR in Morningside Heights',
    shortDescription: 'Corner three-bedroom with Columbia University views.',
    description: 'Generous corner three-bedroom with tree-top views in Morningside Heights. South and west-facing windows provide abundant natural light throughout the day. Spacious living room with built-in bookshelves, eat-in kitchen with dishwasher, and ample closet space. Surrounded by Columbia University, Riverside Church, and the Cathedral of St. John the Divine.',
    price: 3600,
    location: 'Manhattan, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
    status: 'active' as const,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['wifi', 'laundry', 'ac', 'kitchen', 'hardwood', 'dishwasher', 'elevator', 'storage'],
    size: 1100,
    balconies: 0,
    floor: 6,
    totalFloors: 8,
    furnishing: 'unfurnished' as const,
    condition: 'good' as const,
    utilities: ['water', 'gas'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 3600,
    advancePayment: 1800,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'not-allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. No pets. Quiet building with academic residents. Laundry in basement.',
    rentalTerms: '12-month lease. One month security deposit. Heat and hot water included.',
    fullAddress: '420 Riverside Dr, Manhattan, NY 10025',
    lat: 40.8085,
    lng: -73.9635,
    availableFrom: new Date('2026-09-01'),
  },
  {
    title: 'Chic 1BR in Williamsburg',
    shortDescription: 'Designer one-bedroom with private roof access.',
    description: 'Stylish one-bedroom in a boutique Williamsburg building. Interior designed with custom millwork, matte black fixtures, and herringbone tile in the bathroom. Private rooftop access with panoramic views of the Manhattan skyline. The neighborhood offers world-class dining, vintage shopping, and the vibrant Bedford Ave scene.',
    price: 3100,
    location: 'Brooklyn, NY',
    propertyType: 'apartment' as const,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800'],
    status: 'active' as const,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'dishwasher', 'elevator', 'views', 'hardwood', 'laundry'],
    size: 650,
    balconies: 0,
    floor: 4,
    totalFloors: 5,
    furnishing: 'semi-furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'none' as const,
    internet: true,
    securityDeposit: 3100,
    advancePayment: 3100,
    leaseDuration: 12,
    minStay: 6,
    rentFrequency: 'monthly' as const,
    petPolicy: 'case-by-case' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking. Rooftop available until midnight. No glass on roof.',
    rentalTerms: '12-month lease. Two months security deposit. Internet included in rent.',
    fullAddress: '155 N 7th St, Brooklyn, NY 11249',
    lat: 40.7175,
    lng: -73.9565,
    availableFrom: new Date('2026-08-15'),
  },
  {
    title: 'Sunset Villa with Private Dock',
    shortDescription: 'Waterfront estate with private dock on the Arthur Kill.',
    description: 'Magnificent waterfront estate on Staten Island\'s western shore with a private dock on the Arthur Kill. Six bedrooms, five bathrooms, grand foyer with marble staircase, formal dining room, library, and a chef\'s kitchen with dual islands. The grounds include a swimming pool, tennis court, and manicured gardens leading to the private dock. Perfect for boat owners or those who desire an unparalleled waterfront lifestyle.',
    price: 15000,
    location: 'Staten Island, NY',
    propertyType: 'villa' as const,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    status: 'active' as const,
    bedrooms: 6,
    bathrooms: 5,
    amenities: ['wifi', 'parking', 'pool', 'gym', 'ac', 'fireplace', 'kitchen', 'garage', 'garden', 'patio', 'washer/dryer', 'balcony', 'storage', 'views'],
    size: 6500,
    balconies: 4,
    floor: 1,
    totalFloors: 3,
    furnishing: 'furnished' as const,
    condition: 'excellent' as const,
    utilities: ['electricity', 'water', 'gas', 'internet'],
    parking: 'included' as const,
    internet: true,
    securityDeposit: 30000,
    advancePayment: 15000,
    leaseDuration: 24,
    minStay: 12,
    rentFrequency: 'monthly' as const,
    petPolicy: 'allowed' as const,
    smokingPolicy: 'not-allowed' as const,
    houseRules: 'No smoking inside. Pool hours 8am-10pm. Dock usage requires insurance. Tennis court available dawn to dusk.',
    rentalTerms: '24-month lease required. Security deposit equals 2 months rent. Dock maintenance included. Pool heating seasonal surcharge. Background and credit check mandatory. Minimum household income: 50x monthly rent.',
    fullAddress: '855 Arthur Kill Rd, Staten Island, NY 10306',
    lat: 40.5490,
    lng: -74.2250,
    availableFrom: new Date('2026-10-01'),
  },
];

const reviewComments = [
  { rating: 5, comment: 'Amazing place! The location is perfect and the apartment is exactly as described. Would definitely recommend.' },
  { rating: 4, comment: 'Great apartment overall. The neighborhood is fantastic with lots of restaurants and shops nearby. Only minor issue was noisy neighbors.' },
  { rating: 5, comment: 'Loved living here! The natural light is incredible and the building management is very responsive.' },
  { rating: 3, comment: 'Decent place for the price. Some wear and tear but nothing major. Good location for the commute.' },
  { rating: 4, comment: 'Beautiful space with lots of character. The kitchen could use some updating but overall a great find.' },
  { rating: 5, comment: 'Best apartment I have ever had in the city. Spacious, quiet, and well-maintained. The landlord is excellent.' },
  { rating: 4, comment: 'Solid choice in a great neighborhood. The apartment has good natural light and the closets are spacious.' },
  { rating: 3, comment: 'Okay for the price point. The walls are thin but the location makes up for it. Would consider again.' },
  { rating: 5, comment: 'Perfect for a young professional. Close to everything, safe neighborhood, and the apartment itself is charming.' },
  { rating: 4, comment: 'Really enjoyed my time here. The apartment is well-maintained and the area has a great community feel.' },
  { rating: 5, comment: 'Exceeded my expectations! The photos do not do it justice. Moving in was seamless and the space is wonderful.' },
  { rating: 3, comment: 'Good location but the apartment needs some updates. The heating works well though and the rent is reasonable.' },
  { rating: 4, comment: 'The rooftop views are spectacular. Building amenities are top-notch. Only downside is the elevator wait during peak hours.' },
  { rating: 5, comment: 'Absolute gem in a prime location. The finishes are high-end and the layout is very practical for everyday living.' },
  { rating: 4, comment: 'Great value for the area. The neighborhood has improved significantly over the past year. Would rent again.' },
  { rating: 3, comment: 'A bit smaller than expected from the photos, but the location is unbeatable. Decent storage space.' },
  { rating: 5, comment: 'The outdoor space is a rare find in this city. Loved morning coffee on the patio. Very peaceful retreat.' },
  { rating: 4, comment: 'Well-designed space with clever storage solutions. The updated bathroom is a nice touch. Transit is convenient.' },
  { rating: 5, comment: 'From the moment I walked in, I knew this was the one. Beautiful finishes, great light, and a wonderful block.' },
  { rating: 4, comment: 'Solid apartment in a great location. The doorman is very helpful and the gym is well-equipped. Minor noise from the street.' },
];

const seed = async () => {
  const client = new MongoClient(MONGODB_URI, {
    serverApi: {
      version: ServerApiVersion.v1,
      strict: true,
      deprecationErrors: true,
    },
  });

  try {
    await client.connect();
    console.log('Connected to MongoDB');

    const db = client.db('rentivo');

    // Clear existing data
    await db.collection('user').deleteMany({});
    await db.collection('properties').deleteMany({});
    await db.collection('interactions').deleteMany({});
    await db.collection('reviews').deleteMany({});
    await db.collection('rentals').deleteMany({});
    await db.collection('session').deleteMany({});
    console.log('Cleared existing data');

    // Create demo users
    const ownerPassword = await bcrypt.hash('owner1234', SALT_ROUNDS);
    const renterPassword = await bcrypt.hash('demo1234', SALT_ROUNDS);

    const ownerResult = await db.collection('user').insertOne({
      email: 'owner@demo.com',
      password: ownerPassword,
      role: 'owner',
      name: 'Sarah Chen',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const owner2Result = await db.collection('user').insertOne({
      email: 'owner2@demo.com',
      password: await bcrypt.hash('owner1234', SALT_ROUNDS),
      role: 'owner',
      name: 'Marcus Williams',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const renterResult = await db.collection('user').insertOne({
      email: 'renter@demo.com',
      password: renterPassword,
      role: 'renter',
      name: 'Alex Rivera',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const ownerId = ownerResult.insertedId;
    const owner2Id = owner2Result.insertedId;
    const renterId = renterResult.insertedId;

    console.log(`Created owner: owner@demo.com (id: ${ownerId})`);
    console.log(`Created owner: owner2@demo.com (id: ${owner2Id})`);
    console.log(`Created renter: renter@demo.com (id: ${renterId})`);

    // Create properties (split between two owners)
    const propertyResults = await db.collection('properties').insertMany(
      demoProperties.map((p, i) => ({
        ...p,
        ownerId: i % 2 === 0 ? ownerId : owner2Id,
        createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(),
      }))
    );

    const propertyIds = Object.values(propertyResults.insertedIds);
    console.log(`Created ${propertyIds.length} properties`);

    // Create interaction history for the renter
    const interactions: any[] = [];

    // View all properties
    for (const propertyId of propertyIds) {
      interactions.push({
        userId: renterId,
        propertyId,
        type: 'view',
        createdAt: new Date(Date.now() - Math.random() * 14 * 24 * 60 * 60 * 1000),
      });
    }

    // Save some properties (indices 0, 1, 4, 6, 8, 12, 15, 20, 25)
    const savedIndices = [0, 1, 4, 6, 8, 12, 15, 20, 25];
    for (const idx of savedIndices) {
      interactions.push({
        userId: renterId,
        propertyId: propertyIds[idx],
        type: 'save',
        createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000),
      });
    }

    await db.collection('interactions').insertMany(interactions);
    console.log(`Created ${interactions.length} interactions for demo renter`);

    // Create reviews (from a third user for variety)
    const reviewerResult = await db.collection('user').insertOne({
      email: 'reviewer@demo.com',
      password: await bcrypt.hash('review1234', SALT_ROUNDS),
      role: 'renter',
      name: 'Jordan Park',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const reviewerId = reviewerResult.insertedId;
    console.log(`Created reviewer: reviewer@demo.com (id: ${reviewerId})`);

    // Add reviews to the first 15 properties
    const reviews: any[] = [];
    for (let i = 0; i < 15 && i < propertyIds.length; i++) {
      const reviewData = reviewComments[i];
      reviews.push({
        userId: reviewerId,
        propertyId: propertyIds[i],
        rating: reviewData.rating,
        comment: reviewData.comment,
        createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(),
      });
    }

    await db.collection('reviews').insertMany(reviews);
    console.log(`Created ${reviews.length} reviews`);

    console.log('\n--- Seed Complete ---');
    console.log('Demo accounts:');
    console.log('  Owner:  owner@demo.com  / owner1234');
    console.log('  Renter: renter@demo.com / demo1234');
    console.log(`  Properties: ${propertyIds.length}`);
    console.log(`  Interactions: ${interactions.length}`);
    console.log(`  Reviews: ${reviews.length}`);
  } finally {
    await client.close();
  }
};

seed().catch(console.error);
